Rename run to gosa

diff --git a/gosa b/gosa
--- a/gosa
+++ b/gosa
@@ -3,10 +3,20 @@
 config="example"
 
 abort() {
-    echo "Stopped GOsa process. 'gosa-next' container is keept running. Use 'run --stop' to stop it."
+    echo "Stopped GOsa process. 'gosa-next' container is keept running. Use 'gosa --stop' to stop it."
 }
 
 trap 'abort' SIGINT
+
+if ! command docker &> /dev/null; then
+    echo "Can't find the docker binary. Please make sure it is installed."
+    exit 9
+fi
+
+if ! docker info &> /dev/null; then
+    echo "Make sure your docker daemon is running and you're permitted to access it."
+    exit 9
+fi
 
 if [ ! -d .env ]; then
     if command -v virtualenv-3.5 >/dev/null 2>&1; then
@@ -29,7 +39,7 @@ if [[ $? -ne 4 ]]; then
     exit 1
 fi
 
-PARSED=`getopt --options dr --longoptions devel,reset,stop,update,config: --name "$0" -- "$@"`
+PARSED=`getopt --options dr --longoptions devel,reset,stop,update,init,config: --name "$0" -- "$@"`
 if [[ $? -ne 0 ]]; then
 echo "HELP"
     exit 2
@@ -51,7 +61,7 @@ while true; do
             config=$2
             shift 2
             ;;
-        --update)
+        --update|--init)
             update=1
             shift
             ;;
@@ -109,6 +119,11 @@ if [[ $reset -eq 1 ]]; then
     if [[ $cid != "" ]]; then
         docker rm $cid
     fi
+fi
+
+if ! command gosa &> /dev/null; then
+    echo "Please run './gosa --init' first."
+    exit 8
 fi
 
 # Run in devel mode
